language: python
python:
  - "2.7"
# command to install dependencies
install:
  - python setup.py install
#  - pip install -r requirements.txt
  - pip install coveralls

# command to run tests
script:
#python setup.py test
  - python iotqatools/tests/cb_utils_tests.py

after_success:
  coveralls

branches:
  only:
    - develop
    - master

